/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import static Principal.MenuPrincipal.panelPrincipal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class EditarCliente extends javax.swing.JPanel {

    /**
     * Creates new form EditarCliente
     * @param idEditarCliente
     */
    public boolean regresar, noAnt=false;
    public int idCliente =-1, buscar_index = -1 ;
    
    
    public void habilitarRellenarClientes(Cliente cliente_editar){
        labelNombre.setEnabled(true);
        labelEmpresa.setEnabled(true);
        labelPuesto.setEnabled(true);
        labelRFC.setEnabled(true);
        labelEmbarcar.setEnabled(true);
        labelTelefono.setEnabled(true);
        labelDireccion.setEnabled(true);
        labelContacto.setEnabled(true);
        labelEmail.setEnabled(true);
        
        
        
        labelNombre.setText(cliente_editar.nombre);
        labelEmpresa.setText(cliente_editar.empresa);
        labelPuesto.setText(cliente_editar.puesto);
        labelRFC.setText(cliente_editar.rfc);
        labelEmbarcar.setText(cliente_editar.embarcar);
        labelTelefono.setText(cliente_editar.telefono);
        labelDireccion.setText(cliente_editar.domicilio);
        labelContacto.setText(cliente_editar.contacto);
        labelEmail.setText(cliente_editar.correo);
    }
    
    
    public EditarCliente(int idEditarCliente) throws ClassNotFoundException, SQLException {
        initComponents();
        this.idCliente = idEditarCliente;
        regresar = true;
        btnBuscar.setVisible(false);
        comboClientes.setVisible(false);
        Cliente cliente_editar = null;
        for(int i = 0; i<MenuPrincipal.ClientesMuestra.size();i++){
            
            if(idEditarCliente == MenuPrincipal.ClientesMuestra.get(i).id_cliente){
                cliente_editar = MenuPrincipal.ClientesMuestra.get(i);
                break;
            }
        }
        
       
        //ResultSet resultado = MenuPrincipal.consultas.DatosCliente(this.idCliente);
        noAnt = true;
        habilitarRellenarClientes(cliente_editar);
        

    }
    public EditarCliente(){
        initComponents();
        int n = MenuPrincipal.ClientesMuestra.size();
        String arreglo_clientes[] = new String[n];
        
        for(int i = 0; i<n;i++){
            arreglo_clientes[i] = MenuPrincipal.ClientesMuestra.get(i).nombre + " - " + MenuPrincipal.ClientesMuestra.get(i).empresa ;
        }
        
        comboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(arreglo_clientes));
        
        labelNombre.setEnabled(false);
        labelEmpresa.setEnabled(false);
        labelPuesto.setEnabled(false);
        labelRFC.setEnabled(false);
        labelEmbarcar.setEnabled(false);
        labelTelefono.setEnabled(false);
        labelDireccion.setEnabled(false);
        labelContacto.setEnabled(false);
        labelEmail.setEnabled(false);
        
        regresar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        buged = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        labelPuesto = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        comboClientes = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        labelContacto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labelRFC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelDireccion = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelEmbarcar = new javax.swing.JTextArea();

        jLabel9.setText("EMAIL*:");

        setMaximumSize(new java.awt.Dimension(879, 670));
        setMinimumSize(new java.awt.Dimension(879, 670));
        setPreferredSize(new java.awt.Dimension(879, 670));

        jLabel1.setText("Editar Cliente");

        jLabel2.setText("Nombre*:");

        jLabel3.setText("Empresa:");

        jLabel4.setText("Puesto:");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        comboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel5.setText("EMAIL*:");

        jLabel6.setText("Contacto:");

        jLabel7.setText("RFC:");

        labelRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                labelRFCKeyTyped(evt);
            }
        });

        jLabel8.setText("Telefono:");

        labelTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                labelTelefonoKeyTyped(evt);
            }
        });

        jLabel10.setText("Direccion:");

        labelDireccion.setColumns(20);
        labelDireccion.setRows(5);
        jScrollPane1.setViewportView(labelDireccion);

        jLabel11.setText("Embarcar A:");

        labelEmbarcar.setColumns(20);
        labelEmbarcar.setRows(5);
        jScrollPane2.setViewportView(labelEmbarcar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(48, 48, 48)
                        .addComponent(btnRegresar)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPuesto)
                            .addComponent(labelEmpresa)
                            .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelContacto)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(256, 256, 256))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(29, 29, 29)))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addComponent(btnModificar))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        if(regresar){
            VerClientes mi = new VerClientes();
            mi.setLocation(0,0);//posicion del panel ajustado al frame
            mi.setSize(1250, 720);//tamaño del panel ajustado al frame
            /* Esto ultimo es para colocar el panel dentro del frame y ajustarlo en el centro*/
            panelPrincipal.removeAll();
            panelPrincipal.add(mi);
            panelPrincipal.setLocation(0,0);
            panelPrincipal.setSize(1250, 720);
            panelPrincipal.revalidate();
            panelPrincipal.repaint();
        }else{
            MenuClientes mp = new MenuClientes();//declaramos el objeto panel MenuProductos
            mp.setLocation(140,0);//posicion del panel ajustado al frame
            mp.setSize(960, 720);//tamaño del panel ajustado al frame
            /* Esto ultimo es para colocar el panel dentro del frame y ajustarlo en el centro*/
            panelPrincipal.removeAll();
            panelPrincipal.add(mp);
            panelPrincipal.setLocation(0,0);
            panelPrincipal.setSize(1250, 720);
            panelPrincipal.revalidate();
            panelPrincipal.repaint();
        }
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        
        buscar_index = comboClientes.getSelectedIndex();
        Cliente cliente_editar = MenuPrincipal.ClientesMuestra.get(buscar_index);
        
        habilitarRellenarClientes(cliente_editar);   
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        
            
            
        Cliente cliente_ant =null; //cliente anterior para comparar con el nuevo
        if (buscar_index!=-1){
           cliente_ant = MenuPrincipal.ClientesMuestra.get(buscar_index);
        }else{
            if(!noAnt){
                JOptionPane.showMessageDialog(null, "No se encontro cliente");
                return;
            }
        }
        
        if(idCliente !=-1 && noAnt){
             try {
                 cliente_ant = MenuPrincipal.consultas.DatosCliente(idCliente);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(EditarCliente.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(EditarCliente.class.getName()).log(Level.SEVERE, null, ex);
             }
        }else{
            JOptionPane.showMessageDialog(null, "Error");
        }
        
        String nombre = labelNombre.getText();
        String empresa = labelEmpresa.getText();
        String puesto = labelPuesto.getText();
        String rfc = labelRFC.getText(),domicilio= labelDireccion.getText(),
        embarcar =labelEmbarcar.getText(),contacto=labelContacto.getText(),
        telefono=labelTelefono.getText(), correo = labelEmail.getText() ;
        int id = cliente_ant.id_cliente;
        
       Validaciones validar =  new Validaciones();
        
       if(!validar.isValidEmailAddress(correo)){
           JOptionPane.showMessageDialog(null, "El correo no tiene el formato adecuado, o no es valido");
           return;
       }
       
       if(!validar.validarRfc(rfc)){
           JOptionPane.showMessageDialog(null, "El RFC no tiene el formato adecuado, o no es valido");
           return;
       }
        
        
        Cliente cliente = new Cliente(id,nombre,puesto,empresa); //Cliente nuevo para verificar si no esta repetido
        cliente.setCorreo(correo);
        cliente.setRfc(rfc);
        cliente.setDomicilio(domicilio);
        cliente.setTelefono(telefono);
        cliente.setContacto(contacto);
        cliente.setEmbarcar(embarcar);
        
        
        
        
        if(cliente_ant.equals(cliente) ){
            JOptionPane.showMessageDialog(null, "No hay cambios en el cliente");
            
            
        }else{
            
            
            String update_sql = "UPDATE clientes SET nombre = '"+ nombre+ "', apellido = '"+puesto + "', empresa = '"+ empresa+"', email = '"+
                    correo+"', contacto = '"+contacto +"', telefono = '"+telefono +"',rfc =  '"+rfc +"',domicilio = '"+domicilio +"', embarcar = '"+embarcar +"'"+ 
                                    " WHERE id_cliente = " + String.valueOf(id) + ";" ;
            
            
            try {
                MenuPrincipal.consultas.cambiosProducto(update_sql);
                MenuPrincipal.consultas.CargaClientes();//cargaClientes
                if(idCliente == -1){
                    labelNombre.setText("");
                    labelEmpresa.setText("");
                    labelPuesto.setText("");
                    labelRFC.setText("");
                    labelEmbarcar.setText("");
                    labelTelefono.setText("");
                    labelDireccion.setText("");
                    labelContacto.setText("");
                    labelEmail.setText("");
                    
                    labelNombre.setEnabled(false);
                    labelEmpresa.setEnabled(false);
                    labelPuesto.setEnabled(false);
                    labelRFC.setEnabled(false);
                    labelEmbarcar.setEnabled(false);
                    labelTelefono.setEnabled(false);
                    labelDireccion.setEnabled(false);
                    labelContacto.setEnabled(false);
                    labelEmail.setEnabled(false);
                }else{
                    btnRegresarActionPerformed(null);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(EditarCliente.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al modificar");
                return;
            }
            
            JOptionPane.showMessageDialog(null, "Se modifico correctamente");
        }
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void labelTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelTelefonoKeyTyped
        // TODO add your handling code here:
        
         Validaciones validaciones = new Validaciones();
        char ch = evt.getKeyChar();

        if ( !validaciones.isNumber(ch) && !validaciones.isValidSignal(ch,labelTelefono) && !validaciones.validatePoint(ch,labelTelefono)  && ch != '\b') {
                 evt.consume();
         }
        
        if(labelTelefono.getText().length() > 9){
                evt.consume();
        }
    }//GEN-LAST:event_labelTelefonoKeyTyped

    private void labelRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelRFCKeyTyped
        // TODO add your handling code here:
         if(labelRFC.getText().length() > 12){
                evt.consume();
        }   
    }//GEN-LAST:event_labelRFCKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField buged;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField labelContacto;
    private javax.swing.JTextArea labelDireccion;
    private javax.swing.JTextField labelEmail;
    private javax.swing.JTextArea labelEmbarcar;
    private javax.swing.JTextField labelEmpresa;
    private javax.swing.JTextField labelNombre;
    private javax.swing.JTextField labelPuesto;
    private javax.swing.JTextField labelRFC;
    private javax.swing.JTextField labelTelefono;
    // End of variables declaration//GEN-END:variables
}
