/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import static Principal.MenuPrincipal.panelPrincipal;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.SwingUtilities;
/*
 * @author HP y Polette
 */
public class MenuInicial extends javax.swing.JPanel {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        
        initComponents();
        try {
            MenuPrincipal.consultas.CargaDeProducto();//cargar base de datos con productos
            MenuPrincipal.consultas.CargaClientes();//cargaClientes
            MenuPrincipal.CotizacionActual = new Cotizacion(MenuPrincipal.consultas.UnID("Select count(*) From cotizacion") + 1,0.16,0.00); //inicializamos cotizacion con datos actuales
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelWelcome = new javax.swing.JPanel();
        iconClose = new javax.swing.JPanel();
        iconCotizador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuP = new javax.swing.JPanel();
        menuI = new javax.swing.JPanel();
        linehideMenu = new javax.swing.JPanel();
        hideMenu = new javax.swing.JPanel();
        buttonhideMenu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnOpciones = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        menuB = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCotizaciones = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSalirSistema = new javax.swing.JButton();

        setBackground(new java.awt.Color(65, 65, 65));
        setMaximumSize(new java.awt.Dimension(960, 720));
        setMinimumSize(new java.awt.Dimension(960, 720));
        setPreferredSize(new java.awt.Dimension(960, 720));

        PanelWelcome.setBackground(new java.awt.Color(0, 0, 51));
        PanelWelcome.setPreferredSize(new java.awt.Dimension(960, 100));
        PanelWelcome.setLayout(new java.awt.BorderLayout());

        iconClose.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout iconCloseLayout = new javax.swing.GroupLayout(iconClose);
        iconClose.setLayout(iconCloseLayout);
        iconCloseLayout.setHorizontalGroup(
            iconCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        iconCloseLayout.setVerticalGroup(
            iconCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PanelWelcome.add(iconClose, java.awt.BorderLayout.LINE_END);

        iconCotizador.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout iconCotizadorLayout = new javax.swing.GroupLayout(iconCotizador);
        iconCotizador.setLayout(iconCotizadorLayout);
        iconCotizadorLayout.setHorizontalGroup(
            iconCotizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        iconCotizadorLayout.setVerticalGroup(
            iconCotizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PanelWelcome.add(iconCotizador, java.awt.BorderLayout.LINE_START);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(227, 226, 226));
        jLabel1.setText("COTIZADOR");
        PanelWelcome.add(jLabel1, java.awt.BorderLayout.CENTER);

        menuP.setLayout(new java.awt.BorderLayout());

        menuI.setBackground(new java.awt.Color(0, 0, 51));
        menuI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehideMenu.setBackground(new java.awt.Color(0, 0, 51));
        linehideMenu.setLayout(new java.awt.BorderLayout());
        menuI.add(linehideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        hideMenu.setBackground(new java.awt.Color(0, 0, 51));
        hideMenu.setLayout(new java.awt.BorderLayout());

        buttonhideMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhideMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icons/home 30px.png"))); // NOI18N
        buttonhideMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhideMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhideMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhideMenuMouseExited(evt);
            }
        });
        hideMenu.add(buttonhideMenu, java.awt.BorderLayout.CENTER);

        menuI.add(hideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new java.awt.BorderLayout());
        menuI.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 50));

        btnOpciones.setText("Opciones");
        menuI.add(btnOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        menuI.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 10, 50));

        menuP.add(menuI, java.awt.BorderLayout.LINE_START);

        menuB.setBackground(new java.awt.Color(39, 39, 60));
        menuB.setForeground(new java.awt.Color(58, 58, 73));

        jLabel2.setBackground(new java.awt.Color(207, 219, 231));
        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(175, 190, 206));
        jLabel2.setText("Menu ");

        btnCotizaciones.setBackground(new java.awt.Color(153, 153, 153));
        btnCotizaciones.setText("Cotizaciones");
        btnCotizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotizacionesActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(153, 153, 153));
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(153, 153, 153));
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBLayout = new javax.swing.GroupLayout(menuB);
        menuB.setLayout(menuBLayout);
        menuBLayout.setHorizontalGroup(
            menuBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel2)
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCotizaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        menuBLayout.setVerticalGroup(
            menuBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(84, 84, 84)
                .addComponent(btnCotizaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuP.add(menuB, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(221, 225, 236));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo (6).png"))); // NOI18N

        btnSalirSistema.setBackground(new java.awt.Color(51, 51, 51));
        btnSalirSistema.setForeground(new java.awt.Color(204, 204, 204));
        btnSalirSistema.setText("Salir del sistema");
        btnSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnSalirSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnSalirSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(menuP, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(menuP, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirSistemaActionPerformed
        // TODO add your handling code here: 
        System.exit(0);
    }//GEN-LAST:event_btnSalirSistemaActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        
        MenuProductos mp = new MenuProductos();//declaramos el objeto panel MenuProductos
        mp.setLocation(290,0);//posicion del panel ajustado al frame
        mp.setSize(960, 720);//tamaño del panel ajustado al frame
        /* Esto ultimo es para colocar el panel dentro del frame y ajustarlo en el centro*/
        panelPrincipal.removeAll();
        panelPrincipal.add(mp);
        panelPrincipal.setLocation(0,0);
        panelPrincipal.setSize(1250, 720);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        MenuClientes mp = new MenuClientes();//declaramos el objeto panel MenuProductos
        mp.setLocation(290,0);//posicion del panel ajustado al frame
        mp.setSize(960, 720);//tamaño del panel ajustado al frame
        /* Esto ultimo es para colocar el panel dentro del frame y ajustarlo en el centro*/
        panelPrincipal.removeAll();
        panelPrincipal.add(mp);
        panelPrincipal.setLocation(0,0);
        panelPrincipal.setSize(1250, 720);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnCotizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizacionesActionPerformed
        // TODO add your handling code here:
        MenuCotizaciones mp = new MenuCotizaciones();
        mp.setLocation(290,0);//posicion del panel ajustado al frame
        mp.setSize(960, 720);//tamaño del panel ajustado al frame
        /* Esto ultimo es para colocar el panel dentro del frame y ajustarlo en el centro*/
        panelPrincipal.removeAll();
        panelPrincipal.add(mp);
        panelPrincipal.setLocation(0,0);
        panelPrincipal.setSize(1250, 720);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        
        
    }//GEN-LAST:event_btnCotizacionesActionPerformed

    private void buttonhideMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhideMenuMouseEntered
        // TODO add your handling code here: changecolor (linehideMenu, new Color(240,240,240));
    }//GEN-LAST:event_buttonhideMenuMouseEntered

    private void buttonhideMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhideMenuMouseExited
        // TODO add your handling code here: changecolor (linehideMenu, new Color(240,240,240));

    }//GEN-LAST:event_buttonhideMenuMouseExited

    private void buttonhideMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhideMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonhideMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelWelcome;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCotizaciones;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnSalirSistema;
    private javax.swing.JLabel buttonhideMenu;
    private javax.swing.JPanel hideMenu;
    private javax.swing.JPanel iconClose;
    private javax.swing.JPanel iconCotizador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel linehideMenu;
    private javax.swing.JPanel menuB;
    private javax.swing.JPanel menuI;
    private javax.swing.JPanel menuP;
    // End of variables declaration//GEN-END:variables
}
